# GitHub Repository Data Cleaning

This notebook inspects, validates, and cleans the raw GitHub repository dataset before exporting the processed dataset for further analysis.

In [74]:
import pandas as pd

## 1. Load Raw Dataset

In [75]:
data = r"..\data\raw\github_repositories_raw.csv"
github_df=pd.read_csv(data)

## 2. Initial Dataset Inspection

### Dataset Overview

In [76]:
github_df.head()

,owner,name,description,stars,forks,watchers,repo_size,language,created_at,updated_at,...,open_issues,license,topics,has_issues,has_wiki,has_discussions,archived,default_branch,visibility,url
0,PaddlePaddle,PaddlePaddle/PaddleOCR,Turn any PDF or image document into structured...,90517,11434,90517,1970859,Python,2020-05-08T10:38:16Z,2026-10-02T12:46:09Z,...,248,Apache-2.0,"['ai4science', 'chineseocr', 'document-parsing...",True,False,True,False,main,public,https://github.com/PaddlePaddle/PaddleOCR
1,Z4nzu,Z4nzu/hackingtool,ALL IN ONE Hacking Tool For Hackers,80037,9082,80037,6457,Python,2020-04-11T09:21:31Z,2026-10-02T12:41:44Z,...,155,MIT,"['allinonehackingtool', 'besthackingtool', 'ct...",True,True,False,False,master,public,https://github.com/Z4nzu/hackingtool
2,ultralytics,ultralytics/yolov5,Ultralytics YOLOv5 in PyTorch for object detec...,58105,17459,58105,18147,Python,2020-05-18T03:45:11Z,2026-10-02T09:39:53Z,...,24,AGPL-3.0,"['computer-vision', 'coreml', 'deep-learning',...",True,True,True,False,master,public,https://github.com/ultralytics/yolov5
3,SimplifyJobs,SimplifyJobs/Summer2027-Internships,"Summer 2027 software engineering, data science...",47823,3257,47823,4395571,Python,2020-05-23T20:53:18Z,2026-10-02T13:01:51Z,...,109,NaN,"['data-science', 'fall-2026', 'github', 'inter...",True,False,False,False,dev,public,https://github.com/SimplifyJobs/Summer2027-Int...
4,coqui-ai,coqui-ai/TTS,🐸💬 - a deep learning toolkit for Text-to-Speec...,46097,6166,46097,170196,Python,2020-05-20T15:45:28Z,2026-10-02T12:33:13Z,...,3,MPL-2.0,"['deep-learning', 'glow-tts', 'hifigan', 'melg...",True,True,True,False,dev,public,https://github.com/coqui-ai/TTS

In [105]:
rows,columns=github_df.shape
print("Rows:",rows)
print("Columns:",columns)

Rows: 24162
Columns: 22

In [111]:

print("Name of Columns:")
for col in github_df.columns.tolist():
    print(col)

Name of Columns:
owner
name
description
stars
forks
repo_size
language
created_at
updated_at
created_year
open_issues
license
topics
has_issues
has_wiki
has_discussions
archived
default_branch
visibility
url
license_cleaned
license_category

In [79]:
github_df.dtypes

owner                str
name                 str
description          str
stars              int64
forks              int64
watchers           int64
repo_size          int64
language             str
created_at           str
updated_at           str
created_year       int64
open_issues        int64
license              str
topics               str
has_issues          bool
has_wiki            bool
has_discussions     bool
archived            bool
default_branch       str
visibility           str
url                  str
dtype: object

### Missing Values

In [80]:
github_df.isnull().sum()

owner                 0
name                  0
description         346
stars                 0
forks                 0
watchers              0
repo_size             0
language              4
created_at            0
updated_at            0
created_year          0
open_issues           0
license            6051
topics                0
has_issues            0
has_wiki              0
has_discussions       0
archived              0
default_branch        0
visibility            0
url                   0
dtype: int64

### Duplicate Records

In [112]:
print("Duplicate Rows:",github_df.duplicated().sum())

Duplicate Rows: 0

## 3. Missing Value Treatment

In [82]:
github_df[["description","license"]]=github_df[["description","license"]].fillna("Unknown")

In [83]:
github_df["language"]=github_df["language"].fillna("Python")

### Missing Value Verification

In [84]:
github_df.isnull().sum()

owner              0
name               0
description        0
stars              0
forks              0
watchers           0
repo_size          0
language           0
created_at         0
updated_at         0
created_year       0
open_issues        0
license            0
topics             0
has_issues         0
has_wiki           0
has_discussions    0
archived           0
default_branch     0
visibility         0
url                0
dtype: int64

## 4. Data Type Conversion

In [85]:
github_df["created_at"]=pd.to_datetime(github_df["created_at"])

In [86]:
github_df["updated_at"]=pd.to_datetime(github_df["updated_at"])

In [87]:
github_df.dtypes

owner                              str
name                               str
description                        str
stars                            int64
forks                            int64
watchers                         int64
repo_size                        int64
language                           str
created_at         datetime64[us, UTC]
updated_at         datetime64[us, UTC]
created_year                     int64
open_issues                      int64
license                            str
topics                             str
has_issues                        bool
has_wiki                          bool
has_discussions                   bool
archived                          bool
default_branch                     str
visibility                         str
url                                str
dtype: object

## 5. License Cleaning and Categorization

### License Standardization

In [88]:
github_df["license"].value_counts()

license
MIT                   10113
Unknown                6051
Apache-2.0             3496
NOASSERTION            1548
GPL-3.0                1421
AGPL-3.0                503
BSD-3-Clause            467
GPL-2.0                  88
BSD-2-Clause             82
CC0-1.0                  71
MPL-2.0                  64
LGPL-3.0                 48
Unlicense                40
CC-BY-4.0                32
CC-BY-SA-4.0             25
MIT-0                    22
LGPL-2.1                 19
WTFPL                    15
ISC                      14
EUPL-1.2                 10
UPL-1.0                   8
BSD-3-Clause-Clear        6
EPL-2.0                   5
OFL-1.1                   3
0BSD                      3
BSL-1.0                   3
BSD-4-Clause              1
Artistic-2.0              1
GFDL-1.3                  1
Zlib                      1
MulanPSL-2.0              1
Name: count, dtype: int64

### License Category Assignment

In [89]:
def clean_licenses(df):
    df["license"] = df["license"].astype(str).str.strip()
    mapping = {
        "Unknown": "Unspecified",
        "NOASSERTION": "Unspecified",
        "BSD-3-Clause-Clear": "BSD-3-Clause",
    }
    df["license_cleaned"] = df["license"].replace(mapping)
    return df


def get_license_category(lic):
    permissive = [
        "MIT",
        "Apache-2.0",
        "BSD-3-Clause",
        "BSD-2-Clause",
        "ISC",
        "MIT-0",
        "Unlicense",
        "CC0-1.0",
        "WTFPL",
        "0BSD",
        "BSL-1.0",
        "Zlib",
    ]
    copyleft = ["GPL-3.0", "GPL-2.0", "AGPL-3.0", "LGPL-3.0", "LGPL-2.1", "EUPL-1.2"]

    if lic in ["Unknown", "NOASSERTION", "Unspecified"]:
        return "Unknown / Risk"
    elif lic in permissive:
        return "Permissive (Safe)"
    elif lic in copyleft:
        return "Copyleft (Risky for Commercial)"
    else:
        return "Other"


github_df = clean_licenses(github_df)
github_df["license_category"] = github_df["license_cleaned"].apply(get_license_category)

## 6. Numerical Data Validation

In [90]:
columns = github_df.select_dtypes(include=["number"]).columns.tolist()
for column in columns:
    if column=="created_year":
        invalid_year = (github_df[column] > 2026) |( github_df[column] < 2020)
        print(f"Invalid {column}:",invalid_year.sum())
    else:
        invalid_=github_df[column]<0
        print(f"Invalid {column}:",invalid_.sum())

Invalid stars: 0
Invalid forks: 0
Invalid watchers: 0
Invalid repo_size: 0
Invalid created_year: 0
Invalid open_issues: 0

## 7. Date Consistency Validation

In [114]:
inconsistent_date=github_df["created_at"]>github_df["updated_at"]
print("Inconsistent dates:",inconsistent_date.sum())

Inconsistent dates: 0

## 8. Categorical Data Consistency

In [92]:
categorical_col=["language","license","visibility","default_branch"]
for col in categorical_col:
    unique=github_df[col].nunique()
    print(f"Unique Values in {col}:",unique)
    print(github_df[col].value_counts())
    print()

Unique Values in language: 1
language
Python    24162
Name: count, dtype: int64

Unique Values in license: 31
license
MIT                   10113
Unknown                6051
Apache-2.0             3496
NOASSERTION            1548
GPL-3.0                1421
AGPL-3.0                503
BSD-3-Clause            467
GPL-2.0                  88
BSD-2-Clause             82
CC0-1.0                  71
MPL-2.0                  64
LGPL-3.0                 48
Unlicense                40
CC-BY-4.0                32
CC-BY-SA-4.0             25
MIT-0                    22
LGPL-2.1                 19
WTFPL                    15
ISC                      14
EUPL-1.2                 10
UPL-1.0                   8
BSD-3-Clause-Clear        6
EPL-2.0                   5
OFL-1.1                   3
0BSD                      3
BSL-1.0                   3
BSD-4-Clause              1
Artistic-2.0              1
GFDL-1.3                  1
Zlib                      1
MulanPSL-2.0              1
Name: count, dtype: int64

Unique Values in visibility: 1
visibility
public    24162
Name: count, dtype: int64

Unique Values in default_branch: 233
default_branch
main                                 18032
master                                5554
develop                                144
dev                                     90
release                                 17
                                     ...
windows-claudecode                       1
standalone                               1
computer-use-automation-take-home        1
claude/practical-hopper-i6hsy1           1
V0.0.1                                   1
Name: count, Length: 233, dtype: int64

## 9. Outlier Detection

### IQR-Based Outlier Detection

The Interquartile Range (IQR) method is used to identify potential outliers in repository-level metrics such as stars, forks, repository size, and open issues.

Values below `Q1 − 1.5 × IQR` or above `Q3 + 1.5 × IQR` are flagged as potential outliers. These observations are inspected rather than automatically removed, as highly popular repositories can naturally have unusually large values.

In [93]:
categories = ["stars", "forks", "repo_size", "open_issues"]

In [94]:
Q1=github_df[categories].quantile(0.25)
Q3=github_df[categories].quantile(0.75)
print("Q1:\n",Q1)
print("Q3:\n",Q3)

Q1:
 stars            6.0
forks            1.0
repo_size      203.0
open_issues      0.0
Name: 0.25, dtype: float64
Q3:
 stars            132.00
forks             21.00
repo_size      15717.25
open_issues        5.00
Name: 0.75, dtype: float64

In [95]:
IQR=Q3-Q1
print("IQR:\n",IQR)

IQR:
 stars            126.00
forks             20.00
repo_size      15514.25
open_issues        5.00
dtype: float64

In [96]:
lower_limit=Q1-1.5*IQR
upper_limit=Q3+1.5*IQR
print("Lower Limit:\n",lower_limit)
print("Upper Limit:\n",upper_limit)

Lower Limit:
 stars           -183.000
forks            -29.000
repo_size     -23068.375
open_issues       -7.500
dtype: float64
Upper Limit:
 stars            321.000
forks             51.000
repo_size      38988.625
open_issues       12.500
dtype: float64

In [97]:
for category in categories:
    outliers=github_df[(github_df[category]<lower_limit[category]) | ( github_df[category]>upper_limit[category])]
    print(f"Outliers in {category}: {len(outliers)}")

Outliers in stars: 3885

Outliers in forks: 3785
Outliers in repo_size: 3679
Outliers in open_issues: 3678

## 10. Relationship Consistency

This check verifies the relationship between repository stars and forks and identifies repositories where the number of forks exceeds the number of stars for further inspection.

In [98]:
forks_vs_stars=github_df["forks"]>github_df["stars"]
print(forks_vs_stars.sum())

571

### Forks Greater Than Stars Inspection

In [99]:
github_df[forks_vs_stars][["name","stars","forks","url"]]

,name,stars,forks,url
249,Kalebu/Real-time-Vehicle-Dection-Python,37,38,https://github.com/Kalebu/Real-time-Vehicle-De...
314,roerohan/CTF-Write-ups,6,18,https://github.com/roerohan/CTF-Write-ups
340,rzr/awox-mesh-light-webthing,1,2,https://github.com/rzr/awox-mesh-light-webthing
372,SamiAlavi/WebScraper-Nordstrom,0,1,https://github.com/SamiAlavi/WebScraper-Nordstrom
695,aitzaz/udacity-DEND-airflow,0,6,https://github.com/aitzaz/udacity-DEND-airflow
...,...,...,...,...
23519,Cweamy/Anime-Expeditions-Creams-Macro,27,29,https://github.com/Cweamy/Anime-Expeditions-Cr...
23597,borborich/pgextassure,2,3,https://github.com/borborich/pgextassure
23733,AyinkxLab/ai-code-assistant,10,62,https://github.com/AyinkxLab/ai-code-assistant
24044,mergeos-bounties/Lappa,13,24,https://github.com/mergeos-bounties/Lappa
24055,mergeos-bounties/ros2-mcp,11,31,https://github.com/mergeos-bounties/ros2-mcp

## 11. Remove Unnecessary Column

In [100]:
github_df=github_df.drop("watchers",axis=1)

## 12. Export Cleaned Dataset

In [102]:
github_df.to_csv(r"..\data\processed\github_repositories_cleaned.csv",index=False)