# PyPI Download History Data Cleaning

In [3]:
import pandas as pd

## 1. Load Raw Dataset

In [4]:
data = r"..\data\raw\pypi_download_history.csv"
df=pd.read_csv(data)

## 2. Initial Dataset Inspection

In [5]:
df.head()

     package_name        date  downloads
0  beautifulsoup4  2026-04-06    9385346
1  beautifulsoup4  2026-04-07   11178998
2  beautifulsoup4  2026-04-08   12648861
3  beautifulsoup4  2026-04-09   11991463
4  beautifulsoup4  2026-04-10   10804752

In [20]:
print("Name of Columns:")
for col in df.columns.tolist():
    print(col)

Name of Columns:
package_name
date
downloads

In [7]:
df.dtypes

package_name      str
date              str
downloads       int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8413 entries, 0 to 8412
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   package_name  8413 non-null   str
 1   date          8413 non-null   str
 2   downloads     8413 non-null   int64
dtypes: int64(1), str(2)
memory usage: 197.3 KB

In [30]:
print("No. of unique values:\n", df.nunique())

No. of unique values:
 package_name      47
date             179
downloads       8408
dtype: int64

In [31]:
rows, columns = df.shape


print("Rows:", rows)


print("Columns:", columns)

Rows: 8413
Columns: 3

## 3. Date Conversion

In [10]:
df["date"]=pd.to_datetime(df["date"])

In [11]:
df["date"].dtypes

dtype('<M8[us]')

## 4. Missing Values and Duplicate Check

In [29]:
df.isnull().sum()

package_name    0
date            0
downloads       0
dtype: int64

In [24]:
print("No. of dulicated rows:",df.duplicated().sum())

No. of dulicated rows: 0

## 5. Package Name Consistency

In [26]:
df["package_name"].value_counts()

package_name
beautifulsoup4           179
seaborn                  179
jupyterlab               179
black                    179
rich                     179
ollama                   179
pytest-asyncio           179
httpx                    179
spacy                    179
tensorflow               179
dask                     179
numpy                    179
redis                    179
click                    179
pydantic                 179
scipy                    179
litellm                  179
datasets                 179
networkx                 179
requests                 179
streamlit                179
docker                   179
gradio                   179
statsmodels              179
pyarrow                  179
polars                   179
matplotlib               179
sympy                    179
torch                    179
xgboost                  179
jupyter                  179
pyspark                  179
pillow                   179
pydantic-settings        179
selenium                 179
boto3                    179
huggingface-hub          179
uvicorn                  179
catboost                 179
sentence-transformers    179
transformers             179
pytest                   179
typer                    179
celery                   179
openai                   179
plotly                   179
opencv-python            179
Name: count, dtype: int64

In [16]:
df["package_name"]=df["package_name"].astype(str).str.strip()

## 6. Download Data Inspection

In [25]:
df["downloads"].describe().reset_index()

   index     downloads
0  count  8.413000e+03
1   mean  1.156782e+07
2    std  1.819722e+07
3    min  8.567200e+04
4    25%  1.267323e+06
5    50%  5.134926e+06
6    75%  1.452233e+07
7    max  1.445074e+08

## 7. Dataset Ordering

In [32]:
df=df.sort_values("date").reset_index(drop=True)

## 8. Final Dataset Export

In [19]:
df.to_csv(r"..\data\processed\pypi_download_history_cleaned.csv",index=False)